//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.PurchasedHistory = new HashSet<PurchasedHistory>();
            this.LoanHistory = new HashSet<LoanHistory>();
        }
    
        public int BookId { get; set; }
        public string Title { get; set; }
        public int AuthorId { get; set; }
        public string ISBN { get; set; }
        public double BuyPrice { get; set; }
        public Nullable<int> BorrowPrice { get; set; }
        public Nullable<int> StockAvailabilty { get; set; }
        public string CoverImage { get; set; }
        public string Description { get; set; }
        public bool Condition { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public Nullable<int> SoldNumber { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }

        [NotMapped]
        public bool TermsOfService { get; set; }

        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedHistory> PurchasedHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanHistory> LoanHistory { get; set; }
    }
}
