//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }
        public string CustomId { get; set; }
        [Required(ErrorMessage = "*")]
        public string FristName { get; set; }
        [Required(ErrorMessage = "*")]
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string UserName { get; set; }

        [Required(ErrorMessage ="*")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage ="*")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string Telephone { get; set; }
    }
}
