//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanHistory
    {
        public int Id { get; set; }
        public System.DateTime Borrowed { get; set; }
        public Nullable<System.DateTime> Returned { get; set; }
        public int BookId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Delay { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual UserAsp UserAsp { get; set; }
    }
}
